### PR TITLE
Conversion from RDP to (eps, delta)-DP by a new Formula

### PR DESCRIPTION
**Pull request by mmalekzadeh**
Summary: We propose to use the state-of-the-art formula for computing `eps` in  `opacus/privacy_analysis.py` method `get_privacy_spent()`.

related to issue: https://github.com/pytorch/opacus/issues/157

Details:

Currently, the computed epsilon from RDP to (epsilon, delta)-DP is the Line 298 in `opacus/privacy_analysis.py` that is ```eps = rdp_vec - math.log(delta) / (orders_vec - 1)```.

The current line is based on `Proposition 3` in the main RDP paper (Mironov2017):
Ilya Mironov. "Renyi differential privacy." IEEE 30th Computer Security Foundations Symposium (CSF). 2017.

However, in the following paper (Balle2020) authors provide a better conversion from RDP to DP:
Borja Balle et al. "Hypothesis testing interpretations and Renyi differential privacy." International Conference on Artificial Intelligence and Statistics. PMLR, 2020.  Particullary, Theorem 21 in the arXiv version https://arxiv.org/abs/1905.09982.

As this new analysis provides us a better bound (i.e. smaller epsilons), it should be more useful to the users of Opacus.

In this pull request:

1. I have replaced Line 298 with the formula proposed in Balle2020 Theorem 21 as explained above.

2.  I have added information about this paper to the description of the method get_privacy_spent().

As the only difference of this new formula, compared to the previous one, is that it gives us smaller epsilons, and the method's functionality does not change, I believe existing unit tests should be sufficient for this change.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs change / refactoring / dependency upgrade

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the **CONTRIBUTING** document and completed the CLA (see **CONTRIBUTING**).
- [x] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Comment by JohnlNguyen** [comment]
Do you think you can add some tests to verify this change?

**Comment by ilyamironov** [comment]
... and the [tutorials](https://github.com/pytorch/opacus/tree/master/tutorials) ought to be updated with new epsilons.

**Comment by mmalekzadeh** [comment]
Hey @JohnlNguyen.
For testing this specific change I couldn't think of any simple test other than a specific example.
Something like this:
```
from opacus import privacy_analysis
def test_privacy_analysis_rdp_conversion(self):
    orders = [1.1, 3.5, 10]
    rdp = [1.5, 2.24, 5.9]
    target_delta = 1e-5
    eps, alpha = privacy_analysis.get_privacy_spent(
        orders, rdp, target_delta
    )
    self.assertAlmostEqual(float(eps), 6.00759, places=2)
    self.assertAlmostEqual(float(alpha), 3.5, places=2)
```
However, I did not see this type of unit test to be used in this project.
Also,  this needs importing `privacy_analysis` which is a separate module, as this test cannot be done using `PrivacyEngine`.

So, I wanted to get some feedback before going on and modify the pull request.

**Comment by JohnlNguyen** [comment]
A test I can think of is 

For any rdp vec
eps_1 = rdp_vec - math.log(delta) / (orders_vec - 1) # Proposition 3
eps_2 = rdp_vec - (np.log(delta) + np.log(orders_vec)) / (orders_vec - 1) + np.log((orders_vec - 1)/orders_vec)

assert eps_2 <= eps_1

**Comment by mmalekzadeh** [comment]
> A test I can think of is
> 
> For any rdp vec
> eps_1 = rdp_vec - math.log(delta) / (orders_vec - 1) # Proposition 3
> eps_2 = rdp_vec - (np.log(delta) + np.log(orders_vec)) / (orders_vec - 1) + np.log((orders_vec - 1)/orders_vec) # theorem 21
> 
> assert eps_2 <= eps_1

Actually, that can be shown by math (let's say `rdp_vec = e`, `delta = d`, `and orders_vec = o`):
```
Proposition 3 > Theorem 21
-->  e - log(d)/(o-1) > e - ( log(d)+log(o) ) / (o-1) ) + log( (o-1) / o ) 
-->  ( log(d)+log(o) ) / (o-1) ) > log(d)/(o-1) + log( (o-1) / o ) 
-->  log(d)+log(o)   >  log(d) + (o-1) log( (o-1) / o ) 
-->  log(o)   >   (o-1) log(o-1)  - (o-1) log(o) 
-->  log(o) + (o-1) log(o)    >   (o-1) log(o-1)  
-->  log(o) + o log(o) - log(o)    >   (o-1) log(o-1)  
 o log(o)   >   (o-1) log(o-1)  
```
As log() is a strictly increasing function then this is true for any order.

**Comment by JohnlNguyen** [comment]
> Actually, that can be shown by math 

Yup, I agree with that, but we want to make sure the code is tested to show that also.

**Comment by mmalekzadeh** [comment]
> > Actually, that can be shown by math
> 
> Yup, I agree with that, but we want to make sure the code is doing it's intended to do. So it'd would be great if you can codify the above.

Sorry, but I don't think using the same line of code (that is added as an update) in its own unit test is a good idea.

**Comment by mmalekzadeh** [comment]
> ... and the [tutorials](https://github.com/pytorch/opacus/tree/master/tutorials) ought to be updated with new epsilons.

I ran the tutorial `building_image_classifier.ipynb`  with this new update, and as expected, the ultimate epsilon is reduced (from 53.54) to 51.45.  The updated tutorial is committed to this pull request.

**Pull request merged**
