### PR TITLE
Fixing conda packaging to include dev_includes in package

### LINKED ISSUE #326: Add conda recipe
## 🚀 Feature

It would be great if a conda recipe could be added.

## Motivation

Conda is a good package manager to combine dependencies that require complicated build chains.

## Pitch

I can add the recipe for conda and put a PR for merge.

## Alternatives

N.A.

## Additional context

N.A.

### PR DESCRIPTION
**Pull request by sarthakpati**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs change / refactoring / dependency upgrade

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the **CONTRIBUTING** document and completed the CLA (see **CONTRIBUTING**).
- [x] All tests passed, and additional code has been covered with new tests.

Fixes #326

### CODE REVIEW

**Comment by sarthakpati** [comment]
This PR fixes the issue highlighted by https://github.com/pytorch/opacus/issues/326#issuecomment-1007731886

**Comment by ashkan-software** [comment]
Thanks a lot for this. I am looking into this and hoping to merge soon!

**Comment by ashkan-software** [comment]
This looks good to me! Thanks for doing this. 

Could you please add these users as the [package managers](https://github.com/conda-forge/staged-recipes/blob/115c7c56b0ecaad86dfd2604d2481f995a8dc3d7/recipes/opacus/meta.yaml#L45)? 
```
ashkan-software
ffuuugor
karthikprasad
alexandresablayrolles
```

Also, I searched a bit about the process of future package updates on conda, but perhaps you can explain here a bit what we should do when we release a new feature? For pip, we push the new release to PyPi. What's the process for conda? Would it get it automatically from PyPi?

**Review by ashkan-software — APPROVED** [review]

**Comment by sarthakpati** [comment]
Thanks! I have added new maintainers: https://github.com/conda-forge/opacus-feedstock/pull/1

Since I created the recipe from PyPi, as long as new packages are pushed there, new packages will be automatically built on conda using their bots (you can see multiple examples of this process [here](https://github.com/conda-forge/torchio-feedstock/pull/39)). This process creates a PR by the conda bot which the maintainer(s) need to approve prior to merge, and I have been adding automerge to the recipes I maintain (an example is [here](https://github.com/conda-forge/torchio-feedstock/pull/41)) which even removes this requirement as long as all the build tests pass. 😄

**Comment by ashkan-software** [comment]
Thanks for the explanation. I think this process makes a lot of sense.

Out of curiousity, can conda install opacus it be done similar to how captum does it (captum.ai for ref)?
`conda install opacus -c pytorch`

(I have imported this PR and as soon as I get an approval, I merge it :)

**Comment by sarthakpati** [comment]
Yes, it is similar [[ref](https://anaconda.org/conda-forge/opacus)]:

`conda install -c conda-forge opacus`

**Comment by ashkan-software** [comment]
Oh, I guess I was not clear in what I was asking. I was asking if we can do

`conda install opacus -c pytorch`
instead of 
`conda install opacus -c conda-forge`

**Comment by ashkan-software** [comment]
Also, do you mind updating here too? :)

- https://opacus.ai (the main page. The source of this is /opacus/website/pages/en/index.js. Just add another option here "Via conda")
- main Opacus Github README
- https://github.com/pytorch/opacus/edit/main/tutorials/README.md

Thanks a lot for this contribution. This was on the list of the things we wanted to do and we are glad you are taking the lead!

**Comment by sarthakpati** [comment]
> Oh, I guess I was not clear in what I was asking. I was asking if we can do
> 
> `conda install opacus -c pytorch` instead of `conda install opacus -c conda-forge`

Ah, no, because the `-c` denotes the channel on which the package is published. I think the [`pytorch` channel](https://anaconda.org/pytorch/repo) is controlled by the pytorch developers (unsure about this), whereas the public can stage recipes to be pushed to the `conda-forge` channel. If you have access to the pytorch channel, you should be able to push the opacus conda recipe there. 

More information: https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/channels.html

**Comment by sarthakpati** [comment]
I have updated the website, but I am not added the tutorials because the conda recipe does not contain the tutorials as of now. We could add it in the next iteration, perhaps?

**Comment by ashkan-software** [comment]
Thanks! We can go ahead and merge this.

Btw, out of curiosity, could you explain what you mean by this?

>  the conda recipe does not contain the tutorials

The PyPi version of Opacus is simply the normal (not dev). So, shouldn't opacus (no matter how it's installed) work with dev_requirements.txt?

**Comment by sarthakpati** [comment]
> The PyPi version of Opacus is simply the normal (not dev). So, shouldn't opacus (no matter how it's installed) work with dev_requirements.txt?

It should, as long as the dev_requirements.txt is present (which it is for the conda recipe and will be after this merge for the pip recipe).

**Pull request closed without merging**
