### PR TITLE
New Jupyter Notebook & README

### PR DESCRIPTION
**Pull request by jmg-74**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Docs change / refactoring / dependency upgrade
(In fact, this notebook is more an new element of doc)
## Motivation and Context / Related issue

It is a proposal of a Jupyter Notebook showing up some basics of PyTorch-DP. 

As the computation of the DP budget is not trivial, it provides some links to main articles for justifications. It also illustrates the influence of the parameters on epsilon.

## How Has This Been Tested (if it applies)

Only verified the results are the same as given on some MNIST examples. No surprise, as it uses the same functions.

## Checklist

- [X ] The documentation is up-to-date with the changes I made.
(A notebook is self-documented by nature, and a README.md provides a sum up)
- [X ] I have read the **CONTRIBUTING** document and completed the CLA (see **CONTRIBUTING**).
- [ ] All tests passed, and additional code has been covered with new tests.
(Not exactly, please see above)

### CODE REVIEW

**Comment by karthikprasad** [comment]
Hello @jmg-74, thank you so much for this contribution. This notebook is a great addition, and is an awesome tutorial. We do have a few comments, but unfortunately reviewing the notebook on github isn't the very convenient.
One high level comment, could you move the notebook from `scripts/` directory to a separate `docs/` directory?

**Comment by jmg-74** [comment]
Great ! Happy it could be useful here.
Do you mean a `docs/` directory at the root of the repository (at the same level as `examples/`) or in `torchdp/` (same level as `scripts/` ?)
Thank you.

**Comment by karthikprasad** [comment]
I should have been clearer earlier, sorry. I meant at the root (at the same level as `examples/`)

**Comment by jmg-74** [comment]
Sorry for leaving this bug (to fix it, I've only add `../torchdp/scripts/` to the path, to call the shell script. No other modification of the notebook).

As GitHub doesn't seems particularly practical to adapt a Jupyter notebook, I'm ready to get in contact differently to simplify the process. Let me know how if you have any idea about it.

Regards.

**Pull request closed without merging**
