### PR TITLE
Throws an error when params in optimizer are not the same as that of module's in `make_private`

### PR DESCRIPTION
**Pull request by deepakagrawal**
Summary: Compare nn.Module.parameters() with list of parameters from all param_groups of optimizer. If they are all not equal then raise error "Module parameters are different than optimizer Parameters"

Differential Revision: D37163873

### CODE REVIEW

**Review by karthikprasad — COMMENTED** [review]
Thanks Deepak! Looks good. Could you also add a simple unit test in privacy_engine_test for this check?

**Comment by karthikprasad** [comment]
Thanks for adding the tests @deepakagrawal! Please also fix the lint failure and it is good to go after that :)

**Comment by deepakagrawal** [comment]
@karthikprasad can you please check the errors. I think they are not related to the changes I made. I fixed the lint failure.

**Review by karthikprasad — APPROVED** [review]
Looks good. Thank you @deepakagrawal!

**Comment by deepakagrawal** [comment]
@karthikprasad pushed the latest commit to github. I will land the diff as well.

**Pull request closed without merging**
