### PR TITLE
Purge stats.py and utils/clipping.py (Unused code)

### PR DESCRIPTION
**Pull request by ffuuugor**
Removing some unused code.

`opacus/utils/clipping.py` is straightforward, I just forgot to remove it along with `per_sample_gradient_clip.py` in the previous PR.

`opacus/utils/stats.py` is different. I'm not sure if it's actually dead code or I just don't understand it's applications. Does anyone remember the context around it?

### CODE REVIEW

**Comment by karthikprasad** [comment]
`opacus/utils/stats.py` was added to capture stats for different clipping strategies for slicing and dicing on TB

**Comment by ffuuugor** [comment]
Does it have any good use cases with the current architecture?
Looks to me like a tb wrapper, heavily tuned for `ClippingStrategy` enum - so my guess would be no?

**Comment by karthikprasad** [comment]
> Does it have any good use cases with the current architecture? Looks to me like a tb wrapper, heavily tuned for `ClippingStrategy` enum - so my guess would be no?

Yup. Purging should be fine. May be change the title of this PR to explicitly state that stats collector is deleted so that we can easily find it later if we have to.

**Review by karthikprasad — APPROVED** [review]

**Comment by alexandresablayrolles** [comment]
In the future this will definitely belong to Opacus-lab! Looks good to me

**Review by alexandresablayrolles — APPROVED** [review]

**Pull request merged**
